version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/rust:buster
    steps:
      - checkout
      - run:
          name: install grcov
          command: cargo install grcov
      - run:
          name: Run test
          command: cargo test
      - run:
          name: Get coverage test
          command: grcov . > coverage/lcov.info
      - run:
          name: uploade coverage to codecov
          command: |
                  curl -Os https://uploader.codecov.io/latest/linux/codecov
                  curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
                  curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig
                  curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --import
                  gpg --verify codecov.SHA256SUM.sig codecov.SHA256SUM
                  shasum -a 256 -c codecov.SHA256SUM
                  chmod +x codecov
                  ./codecov -t $CODECOV_TOKEN
