version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/rust:1.57.0
    steps:
      - checkout
      - run:
          name: install nightly toolchain
          command: |
            rustup toolchain install nightly-x86_64-unknown-linux-gnu
            rustup default nightly-x86_64-unknown-linux-gnu
      - run:
          name: run build
          command: cargo build
      - run:
          name: run test
          command: cargo test
      - run:
          name: generate coverage
          command: |
            cargo install grcov
            rustup component add llvm-tools-preview
            export RUSTFLAGS="-Zinstrument-coverage"
            cargo build --verbose
            LLVM_PROFILE_FILE="suzume-%p-%m.profraw" cargo test --verbose
            grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o coverage/lcov.info
      - run:
          name: uploade coverage to codecov
          command: |
                  curl -Os https://uploader.codecov.io/latest/linux/codecov
                  curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
                  curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig
                  curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --import
                  gpg --verify codecov.SHA256SUM.sig codecov.SHA256SUM
                  shasum -a 256 -c codecov.SHA256SUM
                  chmod +x codecov
                  ./codecov -t $CODECOV_TOKEN
